export default [
  {
    id: 1,
    name: "Monstera Deliciosa",
    nickname: "Swiss Cheese Plant",
    description:
      "Monstera deliciosa, the Swiss cheese plant or split-leaf philodendron is a species of flowering plant native to tropical forests of southern Mexico, south to Panama. It has been introduced to many tropical areas, and has become a mildly invasive species in Hawaii, Seychelles, Ascension Island and the Society Islands",
    family: "Araceae",
    price: 35,
    img: "https://images.unsplash.com/photo-1614594975525-e45190c55d0b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=764&q=80",
    care: {
      light: "low to bright indirect",
      water: "medium",
      temperature: "average",
      humidity: "above average",
      isPetFriendly: false,
    },
  },
  {
    id: 2,
    name: "Alocasia Odora",
    nickname: "Elephant Ear",
    description:
      "Alocasia odora is a flowering plant native to East and Southeast Asia. In Manipur, local name is Hoomu. Alocasia odora can be used as medicine for the treatment of common cold in North Vietnam. The plant is actually inedible when raw because of needle-shaped raphides in the plant cells.",
    family: "Araceae",
    price: 30,
    img: "https://images.unsplash.com/photo-1560515240-2a94a9f04ebe?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=764&q=80",
    care: {
      light: "low to bright indirect",
      water: "medium",
      temperature: "average",
      humidity: "above average",
      isPetFriendly: false,
    },
  },
  {
    id: 3,
    name: "Alocasia Zebrina",
    nickname: "Zebra Alocasia",
    description:
      "Unlike many of its relatives in the Alocasia genus, the Alocasia zebrina is not prized for its foliage— instead, its amazing zebra-like stems steal the show. Native to the Philippines, this tropical aroid is popular as a houseplant around the world although it can also be grown outside in certain climates. The Alocasia zebrina is difficult to find and tricky to grow since it is known for being picky about its growing conditions.",
    family: "Araceae",
    price: 30,
    img: "https://images.unsplash.com/photo-1655382355596-7bf7012a92f1?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=928&q=80",
    care: {
      light: "low to bright indirect",
      water: "medium",
      temperature: "average",
      humidity: "above average",
      isPetFriendly: false,
    },
  },
  {
    id: 4,
    name: "Bird of Paradise",
    nickname: "Orange Bird of Paradise",
    description:
      "The birds-of-paradise are members of the family Paradisaeidae of the order Passeriformes. The majority of species are found in eastern Indonesia, Papua New Guinea and eastern Australia. The family has 45 species in 17 genera.",
    family: "Paradisaeidae",
    price: 30,
    img: "https://images.unsplash.com/photo-1617002663603-2d7a9eba9324?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=764&q=80",
    care: {
      light: "bright indirect",
      water: "medium",
      temperature: "average",
      humidity: "above average",
      isPetFriendly: false,
    },
  },
  {
    id: 5,
    name: "Marble Queen Pothos",
    nickname: "Queen Pothos",
    description: "You'll get caught up in the crossfire!",
    family: "Araceae",
    price: 25,
    img: "https://images.unsplash.com/photo-1613737693063-a3c03b374aaf?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=764&q=80",
    care: {
      light: "low to bright indirect",
      water: "medium",
      temperature: "average",
      humidity: " average",
      isPetFriendly: false,
    },
  },
  {
    id: 6,
    name: "Monstera Deliciosa Albo",
    nickname: "Monstera albo, varigated monstera",
    description:
      "Monstera albo (Monstera deliciosa 'Albo Borsigiana') is a rare and elusive plant that many plant collectors love and adore. This variegated monstera is at the top of many wish lists around the world thanks to its stunning variegation and prestige reputation—with small plants often selling for several hundred dollars. It is a subspecies of the popular Monstera deliciosa, characterized by large patches of white, naturally occurring variegation on split leaves. ",
    family: "Araceae",
    price: 450,
    img: "https://images.unsplash.com/photo-1612189119321-5b8d2bc94a60?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=928&q=80",
    care: {
      light: "bright indirect",
      water: "medium",
      temperature: "average",
      humidity: "above average",
      isPetFriendly: false,
    },
  },
  {
    id: 7,
    name: "Dracaena Trifasciata",
    nickname: "Snake Plant",
    description:
      "Dracaena trifasciata is a species of flowering plant in the family Asparagaceae, native to tropical West Africa from Nigeria east to the Congo. It is most commonly known as the snake plant, Saint George's sword, mother-in-law's tongue, and viper's bowstring hemp, among other names.",
    family: "Asparagaceae",
    price: 35,
    img: "https://images.unsplash.com/photo-1658309833730-126caf501342?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=928&q=80",
    care: {
      light: "low to bright indirect",
      water: "low",
      temperature: "average",
      humidity: "average",
      isPetFriendly: false,
    },
  },
  {
    id: 8,
    name: "Philodendron Prince of Orange",
    nickname: "Philodendron Hybrid",
    description:
      "The Philodendron Prince of Orange gets its name from its uniquely hued leaves, which change color over time. New growth starts a starburst yellow when it first emerges, transitioning first to copper tones, and ultimately settling into darker shades of green.",
    family: "Asparagaceae",
    price: 60,
    img: "https://images.unsplash.com/photo-1658309833628-5181b14024e2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=928&q=80",
    care: {
      light: "low to bright indirect",
      water: "medium",
      temperature: "average",
      humidity: "average",
      isPetFriendly: false,
    },
  },
  {
    id: 9,
    name: "Aglaonema Kiwi",
    nickname: "Chinese Evergreen",
    description:
      "Intense variegation and packed masses of foliage spread out from the centre of this gorgeous aglaonema variety. The leaves boast more creamy white variegation than green, and for that reason it can really flourish in that sunny spot by the window, unlike most of its shade loving cousins, where it will continue to grow brilliantly white.",
    family: "Araceae",
    price: 35,
    img: "https://images.unsplash.com/photo-1659100056606-f745ce8cd83f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=928&q=80",
    care: {
      light: "medium to bright indirect",
      water: "low",
      temperature: "average",
      humidity: "average",
      isPetFriendly: false,
    },
  },
  {
    id: 10,
    name: "Aglaonema Jungle Red",
    nickname: "Chinese Evergreen",
    description:
      "Aglaonema Jungle Red’s green leaves are stylishly striped with pink variegation. Aglaonema is one of the easiest to grow houseplants while it’s also one of the most interesting and decorative ones. We are always pleasantly surprised with the vibrancy of the colours on those plants.",
    family: "Araceae",
    price: 35,
    img: "https://images.unsplash.com/photo-1658309833607-4de9956d0bbd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=928&q=80",
    care: {
      light: "medium to bright indirect",
      water: "low",
      temperature: "average",
      humidity: "average",
      isPetFriendly: false,
    },
  },
  {
    id: 11,
    name: "Mini Mystery Box",
    nickname: "Mini Mystery Box",
    description: "Get 3 random mini plants in 3-inch sized pots.",
    price: 25,
    img: "https://images.unsplash.com/photo-1659683705445-462189a7d2f5?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=928&q=80",
    care: {
      light: "will vary",
      water: "will vary",
      temperature: "will vary",
      humidity: "will vary",
      isPetFriendly: false,
    },
  },
];
